//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeRabbits.KaoList.Web {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeRabbits.KaoList.Web.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   * {0}을 입력하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _0__is_required {
            get {
                return ResourceManager.GetString("{0} is required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   귀하의 이메일 &quot;{0}&quot;으로 비밀번호 재설정 메일이 발송되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string A_password_reset_email_has_been_sent_to_your_email___0__ {
            get {
                return ResourceManager.GetString("A password reset email has been sent to your email \"{0}\"", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이메일로 비밀번호 재설정 메일이 발송되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string A_password_reset_has_been_sent_to_your_email_ {
            get {
                return ResourceManager.GetString("A password reset has been sent to your email.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이미 존재하는 이메일입니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string A_user_that_already_exists_ {
            get {
                return ResourceManager.GetString("A user that already exists.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   계정 잠금과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Account_Lockout {
            get {
                return ResourceManager.GetString("Account Lockout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   계정 잠금 날짜과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Account_lockout_date {
            get {
                return ResourceManager.GetString("Account lockout date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   계정 잠금 해제과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Account_Unlock {
            get {
                return ResourceManager.GetString("Account Unlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   계정 잠금 해제 날짜과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Account_unlock_date {
            get {
                return ResourceManager.GetString("Account unlock date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   로컬 계정을 추가하면 외부 로그인 없이 로그인할 수 있습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Add_a_local_account_so_you_can_log_in_without_an_external_login {
            get {
                return ResourceManager.GetString("Add a local account so you can log in without an external login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   약관 전체 동의과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Agree_to_all_terms {
            get {
                return ResourceManager.GetString("Agree to all terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이벤트 등 알림 메일 수신 동의과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Agree_to_receive_events_and_other_notifications {
            get {
                return ResourceManager.GetString("Agree to receive events and other notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   등록에 필요한 링크가 포함된 이메일이 발송되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string An_email_has_been_sent_to_you_with_a_link_to_register {
            get {
                return ResourceManager.GetString("An email has been sent to you with a link to register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   귀하의 이메일 &apos;{0}&apos;에 등록에 필요한 링크가 포함된 이메일이 발송되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string An_email_has_been_sent_to_your_email___0___with_the_link_you_need_to_register {
            get {
                return ResourceManager.GetString("An email has been sent to your email \'{0}\' with the link you need to register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   귀하의 &apos;{0}&apos; 계정을 연동합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Associate_your_account {
            get {
                return ResourceManager.GetString("Associate your account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   취소하기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CapsLock이 켜져있습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CapsLock_is_enabled {
            get {
                return ResourceManager.GetString("CapsLock is enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   닉네임 변경과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Change_Nickname {
            get {
                return ResourceManager.GetString("Change Nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   비밀번호 변경과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Change_Password {
            get {
                return ResourceManager.GetString("Change Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   로그아웃을 하려면 여기를 클릭하세요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Click_here_to_Logout {
            get {
                return ResourceManager.GetString("Click here to Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이메일 확인과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Confirm_Email {
            get {
                return ResourceManager.GetString("Confirm Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이메일 확인 실패과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Confirm_email_failed {
            get {
                return ResourceManager.GetString("Confirm email failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   비밀번호 확인과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Confirm_Password {
            get {
                return ResourceManager.GetString("Confirm Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   게시글 도배과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Do_spamming {
            get {
                return ResourceManager.GetString("Do spamming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   다음 이메일 주소와 연동하시겠습니까과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Do_you_want_to_integrate_with_the_following_email_addresses {
            get {
                return ResourceManager.GetString("Do you want to integrate with the following email addresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이메일 주소과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Email_Address {
            get {
                return ResourceManager.GetString("Email Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이메일 확인에 실패했습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Email_verification_failed {
            get {
                return ResourceManager.GetString("Email verification failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   외부 로그인과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string External_Login {
            get {
                return ResourceManager.GetString("External Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   외부 로그인 연동과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string External_login_integration {
            get {
                return ResourceManager.GetString("External login integration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   계정 잠금에 대한 문의사항은 문의사항 탭을 이용해주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string For_inquiries_about_account_lockout__please_use_the_Inquiry_tab {
            get {
                return ResourceManager.GetString("For inquiries about account lockout, please use the Inquiry tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   비밀번호 찾기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Forgot_Password {
            get {
                return ResourceManager.GetString("Forgot Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   홈페이지로 이동과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Go_to_homepage {
            get {
                return ResourceManager.GetString("Go to homepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   로그인 페이지로과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Go_to_Login {
            get {
                return ResourceManager.GetString("Go to Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   에 이메일이 발송되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string has_been_emailed {
            get {
                return ResourceManager.GetString("has been emailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   동일한 현상이 지속적으로 발생할 경우, 문의사항 탭에 해당 사항을 문의해주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string If_the_same_phenomenon_continues_to_occur__please_leave_the_relevant_information_in_our_inquiry_form {
            get {
                return ResourceManager.GetString("If the same phenomenon continues to occur, please leave the relevant information " +
                        "in our inquiry form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   문의사항과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Inquery {
            get {
                return ResourceManager.GetString("Inquery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   연동하기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Integrate {
            get {
                return ResourceManager.GetString("Integrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value &apos;{0}&apos; not found in configuration.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InvalidValueName {
            get {
                return ResourceManager.GetString("InvalidValueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   카오리스트과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string KaoList {
            get {
                return ResourceManager.GetString("KaoList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   로그인과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   로그아웃과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   닉네임과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Nickname {
            get {
                return ResourceManager.GetString("Nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   없음과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   비밀번호과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   비밀번호 재설정 이메일 전송 완료과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Password_reset_email_sent {
            get {
                return ResourceManager.GetString("Password reset email sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   비밀번호 초기화가 완료되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Password_reset_is_complete {
            get {
                return ResourceManager.GetString("Password reset is complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이메일을 확인해 회원가입 과정을 마쳐주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Please_check_your_email_and_complete_the_registration_process {
            get {
                return ResourceManager.GetString("Please check your email and complete the registration process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   아래 버튼을 눌러 로그인을 진행해주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Please_click_the_button_below_to_proceed_to_login {
            get {
                return ResourceManager.GetString("Please click the button below to proceed to login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   새로운 비밀번호를 확인하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Please_confirm_your_new_password {
            get {
                return ResourceManager.GetString("Please confirm your new password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   새로운 비밀번호를 입력하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Please_enter_your_new_password {
            get {
                return ResourceManager.GetString("Please enter your new password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   기존 비밀번호를 입력하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Please_enter_your_old_password {
            get {
                return ResourceManager.GetString("Please enter your old password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   개인정보이용방침과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Privacy_Policy {
            get {
                return ResourceManager.GetString("Privacy Policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   계정 잠금 조치 이유과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Reason_for_account_lockout {
            get {
                return ResourceManager.GetString("Reason for account lockout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   회원가입과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   회원가입 확인과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Register_confirmation {
            get {
                return ResourceManager.GetString("Register confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   등록 성공과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Registeraion_Successful {
            get {
                return ResourceManager.GetString("Registeraion Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   로그인 상태 유지과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Remember_Me {
            get {
                return ResourceManager.GetString("Remember Me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   비밀번호 초기화과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Reset_Password {
            get {
                return ResourceManager.GetString("Reset Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   비밀번호 초기화 완료과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Reset_password_confirmation {
            get {
                return ResourceManager.GetString("Reset password confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이메일 전송과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Send_Email {
            get {
                return ResourceManager.GetString("Send Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   패스워드 초기화과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Set_Password {
            get {
                return ResourceManager.GetString("Set Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   소셜 로그인과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Social_Login {
            get {
                return ResourceManager.GetString("Social Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   음란물 유포과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Spreading_pornography {
            get {
                return ResourceManager.GetString("Spreading pornography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   외부 로그인 계정 연동 성공과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Successful_external_login_account_integration {
            get {
                return ResourceManager.GetString("Successful external login account integration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이용약관과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Terms_of_Service {
            get {
                return ResourceManager.GetString("Terms of Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   외부 로그인 계정 연결에 성공하였습니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string The_external_login_account_connection_was_successful {
            get {
                return ResourceManager.GetString("The external login account connection was successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   으로과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string to {
            get {
                return ResourceManager.GetString("to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   홈페이지로과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string To_Homepage {
            get {
                return ResourceManager.GetString("To Homepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   비정상적인 접근과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Unusual_access {
            get {
                return ResourceManager.GetString("Unusual access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   비밀번호 재설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Update_Password {
            get {
                return ResourceManager.GetString("Update Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이 사이트에 대한 로컬 사용자 이름/비밀번호가 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string You_do_not_have_a_local_username_password_for_this_site {
            get {
                return ResourceManager.GetString("You do not have a local username/password for this site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   로그아웃에 성공했습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string You_have_successfully_logged_out {
            get {
                return ResourceManager.GetString("You have successfully logged out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   회원님의 계정이 후술할 이유로 인해 잠금조치 되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Your_account_has_been_locked_for_reasons_described_below {
            get {
                return ResourceManager.GetString("Your account has been locked for reasons described below", resourceCulture);
            }
        }
        
        /// <summary>
        ///   귀하의 이메일 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Your_email {
            get {
                return ResourceManager.GetString("Your email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이메일이 확인되었습니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Your_email_has_been_confirmed {
            get {
                return ResourceManager.GetString("Your email has been confirmed", resourceCulture);
            }
        }
    }
}
